### PR TITLE
Raises an error if the response is not a valid URI

### LINKED ISSUE #11: Remove "to" and "tk" from shorteners?
I see that http://longurl.org/services and [the code](https://github.com/altmetric/embiggen/blob/v0.2.0/lib/embiggen/configuration.rb#L19-L66) have `to` and `tk` as domains for URL shortening services. And [Dot TK](http://www.dot.tk/en/index.html?lang=en) do in fact let you create your own `.tk` domain to shorten any URL you want.

But not all `.tk` (and `.to`?) are URL shortening services, I'm afraid. Here is one example.

```ruby
$ pry
[1] pry(main)> RUBY_VERSION
=> "2.2.2"
[2] pry(main)> require "embiggen"
=> true
[3] pry(main)> url = "http://crafttalk.tk/index.php/260155-working-with-a-carpeting-cleaner-recommendations-and-suggestion/0"
=> "http://crafttalk.tk/index.php/260155-working-with-a-carpeting-cleaner-recommendations-and-suggestion/0"
[4] pry(main)> Embiggen::URI(url).expand
=> #<URI::Generic /index.php/260155-locate-a-excellent-web-host-with-these-ideas/0>
[5] pry(main)> Embiggen::URI(url).expand!
=> #<URI::Generic /index.php/260155-locate-a-excellent-web-host-with-these-ideas/0>
[6] pry(main)> Embiggen::URI(url).shortened?
=> true
```

A bit unexpected to only get the path back (a new path). A closer look at that:

```ruby
[19] pry(main)> uri = URI(Addressable::URI.parse(url).normalize.to_s)
=> #<URI::HTTP http://crafttalk.tk/index.php/260155-working-with-a-carpeting-cleaner-recommendations-and-suggestion/0>
[35] pry(main)> http = ::Net::HTTP.new(uri.host, uri.port)
=> #<Net::HTTP crafttalk.tk:80 open=false>
[36] pry(main)> response = http.head(uri.request_uri)
=> #<Net::HTTPMovedPermanently 301 Moved Permanently readbody=true>
[37] pry(main)> response.is_a?(::Net::HTTPRedirection)
=> true
[38] pry(main)> response.fetch('Location')
=> "/index.php/260155-locate-a-excellent-web-host-with-these-ideas/0"
```

Not sure what the right thing is to do here, maybe there are people expecting this gem to be able to expand arbitrary `.to` and `.tk` domains.

Maybe it is possible to detect that we only got a path from the `Location` header, and append scheme, and host (and port if non standard). But then `#shortened?` isn't really true, in some cases. :)

So the easiest seem to just remove `to` and `tk`.

(This issue is slightly related to #2)

### PR DESCRIPTION
**Pull request by jbilbo**
Checks the `location` response for a valid URI and raises `BadShortenedURI` error in case it isn't.

Fixes #11

### CODE REVIEW

**Comment by jbilbo** [comment]
You know nothing, @houndci

File: lib/embiggen/uri.rb [hunk 1]
```diff
@@ -43,8 +43,17 @@ def follow(request_options = {})
       location = http_client.follow(timeout)
       fail BadShortenedURI.new(
         "following #{uri} did not redirect", uri) unless location
+      check_location(location)
```
Comment (mudge) [inline lib/embiggen/uri.rb]: I wonder if this is the same as the line above: rather than having `unless location` *and* `check_location(location)`, could they be combined into one validity check?

File: lib/embiggen/uri.rb [hunk 2]
```diff
@@ -43,8 +43,17 @@ def follow(request_options = {})
...
 
       location
     end
+
+    def check_location(location)
+      addressable = Addressable::URI.parse(location)
+
+      fail Addressable::URI::InvalidURIError if addressable.host.nil?
```
Comment (mudge) [inline lib/embiggen/uri.rb]: I wonder if we should invert this logic: check the correctness of a URL by looking for *at least* the following:

* A scheme (e.g. `http`);
* A host (e.g. `example.com`);
* A path (e.g. `/`).

**Comment by mudge** [comment]
Re @houndci, we should add a `.hound.yml` with the following:

```yaml
ruby:
  config_file: .rubocop.yml
```

File: lib/embiggen/uri.rb (hunk 1 above)
Comment (jbilbo) [inline lib/embiggen/uri.rb]: Yes, makes sense.

File: lib/embiggen/uri.rb (hunk 2 above)
Comment (jbilbo) [inline lib/embiggen/uri.rb]: Great comments! Updated at f457674. Let me know what you think.

**Comment by jbilbo** [comment]
> Re @houndci, we should add a .hound.yml

Added `.hound.yml`

File: lib/embiggen/uri.rb [hunk 3]
```diff
@@ -41,10 +41,22 @@ def follow(request_options = {})
...
+
+    def check_location(location)
       fail BadShortenedURI.new(
         "following #{uri} did not redirect", uri) unless location
 
-      location
+      parsed_uri = Addressable::URI.parse(location)
+      return if parsed_uri.scheme && parsed_uri.host && parsed_uri.path
+
+      fail Addressable::URI::InvalidURIError
```
Comment (mudge) [inline lib/embiggen/uri.rb]: I wonder if these are actually two separate cases and we shouldn't fake an `InvalidURIError` here:

1. The returned location is genuinely an invalid URI (which is surprisingly rare but can be triggered with the URI `::http`);
2. The returned location is a URI but we can't follow it because it's not absolute.

I think we could actually use Addressable's `absolute?` as the check here, e.g.

```ruby
  location = http_client.follow(timeout)
  fail BadShortenedURI.new("cannot follow #{uri}'s redirection", uri) unless followable?(location)

  location
end

def followable?(location)
  return unless location

  Addressable::URI.parse(location).absolute?
rescue Addressable::URI::InvalidURIError => e
  raise BadShortenedURI.new("following #{uri} returns an invalid URI: #{e}", uri)
end
```
